[package]
name = "well-config"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.29"
well-ipc = { path = "../well-ipc" }
well-core = { path = "../well-core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
well-llm = { path = "../well-llm" }
arboard = "3.6.1"
keyring = "4.2.0"

[dev-dependencies]
egui_extras = { version = "0.36.2", features = ["all_loaders", "image"] }
